name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: apt update
      run: apt update
    - name: apt install
      run: apt install -y protobuf-compiler
    - name: Check
      run: cargo check
    - name: Clippy
      run: cargo clippy
